<?php
return array(
    'crm_adhoc_group' => array(
        'adhoc_id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('contact_id', 'adhoc_id'),
            'adhoc_id' => 'adhoc_id',
        ),
    ),
    'crm_call' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'direction' => array('enum', "'IN','OUT'", 'null' => 0),
        'status_id' => array('enum', "'PENDING','CONNECTED','DROPPED','REDIRECTED','FINISHED','VOICEMAIL'", 'default' => 'PENDING'),
        'create_datetime' => array('datetime', 'null' => 0),
        'finish_datetime' => array('datetime'),
        'plugin_id' => array('varchar', 64, 'null' => 0),
        'plugin_call_id' => array('varchar', 255, 'null' => 0),
        'plugin_gateway' => array('varchar', 255),
        'plugin_user_number' => array('varchar', 255),
        'plugin_client_number' => array('varchar', 255),
        'plugin_record_id' => array('varchar', 255),
        'notification_sent' => array('tinyint', 4, 'null' => 0, 'default' => '0'),
        'deal_id' => array('int', 11),
        'client_contact_id' => array('int', 11),
        'user_contact_id' => array('int', 11),
        'duration' => array('int', 11, 'null' => 0, 'default' => '0'),
        'comment' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'status_id' => 'status_id',
            'call_id' => array('plugin_id', 'plugin_call_id'),
            'client_contact_id' => 'client_contact_id',
            'user_contact_id' => 'user_contact_id',
            'deal_id' => 'deal_id',
            'notification_sent' => 'notification_sent',
        ),
    ),
    'crm_call_params' => array(
        'call_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 32, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('call_id', 'name'),
        ),
    ),
    'crm_company' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        'phone' => array('varchar', 255),
        'address' => array('text'),
        'tax_name' => array('varchar', 255),
        'tax_options' => array('text'),
        'logo' => array('varchar', 10),
        'template_id' => array('int', 11, 'null' => 0),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'crm_company_params' => array(
        'company_id' => array('int', 11, 'null' => 0),
        'template_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'value' => array('varchar', 255),
        ':keys' => array(
            'PRIMARY' => array('company_id', 'template_id', 'name'),
        ),
    ),
    'crm_contact_tags' => array(
        'contact_id' => array('int', 11, 'null' => 0),
        'tag_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('contact_id', 'tag_id'),
        ),
    ),
    'crm_conversation' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'create_datetime' => array('datetime', 'null' => 0),
        'update_datetime' => array('datetime', 'null' => 0),
        'source_id' => array('int', 11, 'null' => 0),
        'type' => array('enum', "'EMAIL','IM'", 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'user_contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'deal_id' => array('int', 11),
        'summary' => array('varchar', 255),
        'last_message_id' => array('int', 11),
        'count' => array('int', 11, 'null' => 0, 'default' => '0'),
        'is_closed' => array('int', 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'source_id' => 'source_id',
            'contact_id' => 'contact_id',
            'user_contact_id' => 'user_contact_id',
            'deal_id' => 'deal_id',
        ),
    ),
    'crm_currency' => array(
        'code' => array('char', 3, 'null' => 0),
        'rate' => array('decimal', "15,8", 'null' => 0, 'default' => '1.00000000'),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'code',
        ),
    ),
    'crm_deal' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'creator_contact_id' => array('int', 11, 'null' => 0),
        'create_datetime' => array('datetime', 'null' => 0),
        'update_datetime' => array('datetime', 'null' => 0),
        'reminder_datetime' => array('datetime'),
        'funnel_id' => array('int', 11, 'null' => 0),
        'stage_id' => array('int', 11, 'null' => 0),
        'status_id' => array('enum', "'OPEN','WON','LOST'", 'null' => 0, 'default' => 'OPEN'),
        'name' => array('varchar', 255, 'null' => 0),
        'description' => array('text'),
        'expected_date' => array('date'),
        'closed_datetime' => array('datetime'),
        'amount' => array('decimal', "15,4"),
        'currency_id' => array('char', 3),
        'currency_rate' => array('decimal', "15,8"),
        'contact_id' => array('int', 11, 'null' => 0),
        'user_contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'lost_id' => array('int', 11),
        'lost_text' => array('varchar', 255),
        'source_id' => array('int', 11),
        'external_id' => array('varchar', 255),
        'last_message_id' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
            'funnel_id' => 'funnel_id',
            'stage_id' => 'stage_id',
            'user_contact_id' => 'user_contact_id',
            'lost_id' => 'lost_id',
            'contact_id' => 'contact_id',
            'source_id' => 'source_id',
            'external_id' => 'external_id',
        ),
    ),
    'crm_deal_lost' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'funnel_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'name' => array('varchar', 255, 'null' => 0),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'funnel_id' => 'funnel_id',
        ),
    ),
    'crm_deal_params' => array(
        'deal_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'value' => array('text'),
        ':keys' => array(
            'PRIMARY' => array('deal_id', 'name'),
        ),
    ),
    'crm_deal_participants' => array(
        'deal_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'role_id' => array('enum', "'USER','CLIENT'", 'null' => 0),
        'label' => array('varchar', 64),
        'create_datetime' => array('datetime', 'null' => 0, 'default' => '2017-10-24 00:00:00'),
        ':keys' => array(
            'PRIMARY' => array('deal_id', 'contact_id', 'role_id'),
        ),
    ),
    'crm_deal_stages' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'deal_id' => array('int', 11, 'null' => 0),
        'stage_id' => array('int', 11, 'null' => 0),
        'in_datetime' => array('datetime', 'null' => 0),
        'out_datetime' => array('datetime'),
        'minutes' => array('int', 11),
        'overdue_datetime' => array('datetime'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'deal_id' => 'deal_id',
            'stage_id' => 'stage_id',
        ),
    ),
    'crm_file' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'creator_contact_id' => array('int', 11, 'null' => 0),
        'create_datetime' => array('datetime', 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'size' => array('int', 11, 'null' => 0),
        'ext' => array('varchar', 10),
        'name' => array('varchar', 255, 'null' => 0),
        'comment' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
        ),
    ),
    'crm_form' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        'create_datetime' => array('datetime', 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'locale' => array('varchar', 5),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'crm_form_params' => array(
        'form_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'value' => array('text'),
        ':keys' => array(
            'PRIMARY' => array('form_id', 'name'),
        ),
    ),
    'crm_funnel' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        'color' => array('varchar', 13, 'null' => 0),
        'open_color' => array('varchar', 13, 'null' => 0),
        'close_color' => array('varchar', 13, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'crm_funnel_stage' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'funnel_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'number' => array('int', 11, 'null' => 0),
        'limit_hours' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
            'funnel_number' => array('funnel_id', 'number', 'unique' => 1),
            'funnel_id' => 'funnel_id',
        ),
    ),
    'crm_invoice' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'create_datetime' => array('datetime', 'null' => 0),
        'update_datetime' => array('datetime', 'null' => 0),
        'number' => array('varchar', 16),
        'invoice_date' => array('date', 'null' => 0),
        'creator_contact_id' => array('int', 11, 'null' => 0),
        'company_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'due_days' => array('int', 11, 'null' => 0, 'default' => '0'),
        'due_date' => array('date'),
        'amount' => array('decimal', "15,4", 'null' => 0),
        'currency_id' => array('char', 3, 'null' => 0),
        'currency_rate' => array('decimal', "15,8", 'null' => 0),
        'tax_name' => array('varchar', 255),
        'tax_percent' => array('decimal', "5,2", 'null' => 0, 'default' => '0.00'),
        'tax_type' => array('enum', "'INCLUDE','APPEND','NONE'", 'null' => 0, 'default' => 'NONE'),
        'tax_amount' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'discount_percent' => array('decimal', "5,2", 'null' => 0, 'default' => '0.00'),
        'discount_amount' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'summary' => array('varchar', 255),
        'comment' => array('text'),
        'state_id' => array('enum', "'PENDING','PAID','REFUNDED','ARCHIVED','DRAFT','PROCESSING'", 'null' => 0, 'default' => 'DRAFT'),
        'payment_datetime' => array('datetime'),
        'deal_id' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
            'company_id' => 'company_id',
            'contact_id' => 'contact_id',
            'state_id' => 'state_id',
            'deal_id' => 'deal_id',
        ),
    ),
    'crm_invoice_items' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'invoice_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'price' => array('decimal', "15,4", 'null' => 0),
        'quantity' => array('decimal', "15,4", 'null' => 0),
        'product_id' => array('varchar', 255),
        'tax_type' => array('enum', "'INCLUDE','APPEND','NONE'", 'null' => 0, 'default' => 'NONE'),
        'tax_percent' => array('decimal', "5,2", 'null' => 0, 'default' => '0.00'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'invoice_id' => 'invoice_id',
        ),
    ),
    'crm_invoice_params' => array(
        'invoice_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 64, 'null' => 0),
        'value' => array('varchar', 255, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('invoice_id', 'name'),
        ),
    ),
    'crm_log' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'create_datetime' => array('datetime', 'null' => 0),
        'actor_contact_id' => array('int', 11, 'null' => 0),
        'action' => array('varchar', 50, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'object_id' => array('int', 11),
        'object_type' => array('enum', "'CONTACT','DEAL','INVOICE','REMINDER','NOTE','FILE','CALL','EMAIL','MESSAGE','ORDER_LOG'", 'null' => 0),
        'before' => array('varchar', 255),
        'after' => array('varchar', 255),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
            'object_type' => 'object_type',
        ),
    ),
    'crm_message' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'create_datetime' => array('datetime', 'null' => 0),
        'creator_contact_id' => array('int', 11, 'null' => 0),
        'transport' => array('enum', "'EMAIL','SMS','IM'", 'null' => 0, 'default' => 'EMAIL'),
        'direction' => array('enum', "'IN','OUT'", 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'deal_id' => array('int', 11),
        'source_id' => array('int', 11),
        'subject' => array('varchar', 255),
        'body' => array('text', 'null' => 0),
        'from' => array('varchar', 255),
        'to' => array('varchar', 255, 'null' => 0),
        'original' => array('tinyint', 4, 'null' => 0, 'default' => '0'),
        'event' => array('varchar', 64),
        'conversation_id' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
            'creator_contact_id' => 'creator_contact_id',
            'contact_id' => 'contact_id',
            'deal_id' => 'deal_id',
            'conversation_id' => 'conversation_id',
        ),
    ),
    'crm_message_attachments' => array(
        'message_id' => array('int', 11, 'null' => 0),
        'file_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'message_file' => array('message_id', 'file_id', 'unique' => 1),
            'message_id' => 'message_id',
        ),
    ),
    'crm_message_params' => array(
        'message_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'name' => array('varchar', 255, 'null' => 0),
        'value' => array('text'),
        ':keys' => array(
            'PRIMARY' => array('message_id', 'name'),
        ),
    ),
    'crm_message_read' => array(
        'message_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('message_id', 'contact_id'),
        ),
    ),
    'crm_message_recipients' => array(
        'message_id' => array('int', 11, 'null' => 0),
        'destination' => array('varchar', 255, 'null' => 0),
        'type' => array('enum', "'TO','CC','BCC','FROM'", 'null' => 0, 'default' => 'CC'),
        'name' => array('varchar', 255),
        'contact_id' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => array('message_id', 'destination'),
            'contact_id' => 'contact_id',
        ),
    ),
    'crm_note' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'create_datetime' => array('datetime', 'null' => 0),
        'creator_contact_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'content' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
        ),
    ),
    'crm_notification' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'event' => array('varchar', 64, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'transport' => array('enum', "'email','sms'", 'null' => 0),
        'status' => array('tinyint', 1, 'null' => 0),
        'subject' => array('varchar', 255),
        'body' => array('text'),
        'recipient' => array('varchar', 255, 'null' => 0, 'default' => 'client'),
        'sender' => array('varchar', 255, 'null' => 0, 'default' => 'system'),
        'company_id' => array('int', 11, 'null' => 1),
        ':keys' => array(
            'PRIMARY' => 'id',
            'event' => 'event',
        ),
    ),
    'crm_payment' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'plugin' => array('varchar', 32, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'description' => array('text'),
        'logo' => array('text'),
        'status' => array('tinyint', 1, 'null' => 0, 'default' => '1'),
        'sort' => array('int', 11, 'null' => 0),
        'company_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'plugin_company' => array('plugin', 'company_id', 'unique' => 1),
            'company_id' => 'company_id',
        ),
    ),
    'crm_payment_settings' => array(
        'id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 64, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id', 'name'),
        ),
    ),
    'crm_pbx' => array(
        'plugin_id' => array('varchar', 64, 'null' => 0),
        'plugin_user_number' => array('varchar', 132, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('plugin_id', 'plugin_user_number'),
        ),
    ),
    'crm_pbx_params' => array(
        'plugin_id' => array('varchar', 64, 'null' => 0),
        'plugin_user_number' => array('varchar', 132, 'null' => 0),
        'name' => array('varchar', 32, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('plugin_id', 'plugin_user_number', 'name'),
        ),
    ),
    'crm_pbx_users' => array(
        'plugin_id' => array('varchar', 64, 'null' => 0),
        'plugin_user_number' => array('varchar', 132, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('plugin_id', 'plugin_user_number', 'contact_id'),
        ),
    ),
    'crm_recent' => array(
        'user_contact_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'is_pinned' => array('tinyint', 4, 'null' => 0, 'default' => '0'),
        'view_datetime' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('user_contact_id', 'contact_id'),
        ),
    ),
    'crm_reminder' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'create_datetime' => array('datetime', 'null' => 0),
        'creator_contact_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11),
        'user_contact_id' => array('int', 11, 'null' => 0),
        'due_date' => array('date', 'null' => 0),
        'due_datetime' => array('datetime'),
        'complete_datetime' => array('datetime'),
        'content' => array('text'),
        'type' => array('enum', "'MEETING','CALL','MESSAGE','OTHER'", 'null' => 0, 'default' => 'OTHER'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
            'type' => 'type',
        ),
    ),
    'crm_segment' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'type' => array('varchar', 32, 'null' => 0),
        'name' => array('varchar', 255),
        'hash' => array('text'),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        'create_datetime' => array('datetime', 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'shared' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'count' => array('int', 11, 'null' => 0, 'default' => '0'),
        'icon' => array('varchar', 255),
        'category_id' => array('int', 11),
        'archived' => array('tinyint', 3, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
            'category_id' => 'category_id',
            'type' => 'type',
        ),
    ),
    'crm_segment_count' => array(
        'segment_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'count' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => array('segment_id', 'contact_id'),
        ),
    ),
    'crm_source' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'creator_contact_id' => array('int', 11, 'null' => 0),
        'create_datetime' => array('datetime', 'null' => 0),
        'type' => array('enum', "'EMAIL','FORM','SHOP','SPECIAL','IM'", 'null' => 0, 'default' => 'SPECIAL'),
        'provider' => array('varchar', 64),
        'name' => array('varchar', 255, 'null' => 0),
        'funnel_id' => array('int', 11),
        'stage_id' => array('int', 11),
        'responsible_contact_id' => array('int', 11),
        'disabled' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'crm_source_params' => array(
        'source_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'value' => array('text'),
        ':keys' => array(
            'PRIMARY' => array('source_id', 'name'),
        ),
    ),
    'crm_tag' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        'count' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'crm_temp' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'hash' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'data' => array('longtext', 'null' => 0),
        'create_datetime' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'hash' => 'hash',
        ),
    ),
    'crm_template' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        'content' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'crm_template_params' => array(
        'template_id' => array('int', 11, 'null' => 0),
        'code' => array('varchar', 64, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'placeholder' => array('varchar', 255),
        'type' => array('enum', "'STRING','COLOR','NUMBER','IMAGE'", 'null' => 0, 'default' => 'STRING'),
        'sort' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('template_id', 'code'),
        ),
    ),
    'crm_vault' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        'color' => array('varchar', 13),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        'create_datetime' => array('datetime', 'null' => 0),
        'count' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
);
