<?php
return array(
    'crm_atolonline_receipt' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'transaction_id' => array('int', 11),
        'invoice_id' => array('int', 11, 'null' => 0),
        'create_datetime' => array('datetime', 'null' => 0),
        'operation' => array('enum', "'sell','sell_refund','sell_correction'", 'null' => 0, 'default' => 'sell'),
        'receipt_data' => array('text', 'null' => 0),
        'customer_email' => array('varchar', 64),
        'customer_phone' => array('varchar', 64),
        'amount' => array('decimal', "10,2", 'null' => 0),
        'retry' => array('int', 11, 'null' => 0, 'default' => '0'),
        'atol_timestamp' => array('datetime'),
        'atol_uuid' => array('varchar', 255),
        'status' => array('enum', "'wait','fail','done'"),
        'error_id' => array('varchar', 64),
        'error_code' => array('int', 11),
        'error_type' => array('enum', "'system','driver','timeout'"),
        'error_text' => array('varchar', 255),
        'atol_daemon_code' => array('varchar', 255),
        'atol_device_code' => array('varchar', 255),
        'receipt_datetime' => array('datetime'),
        'fiscal_receipt_number' => array('int', 11),
        'shift_number' => array('int', 11),
        'fn_number' => array('varchar', 255),
        'ecr_registration_number' => array('varchar', 255),
        'fiscal_document_number' => array('int', 11),
        'fiscal_document_attribute' => array('varchar', 255),
        'fns_site' => array('varchar', 255),
        'perefix_id' => array('varchar', 255),
        'refund_id' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
            'atol_uuid' => array('atol_uuid', 'unique' => 1),
            'invoice_id' => 'invoice_id',
            'transaction_id' => 'transaction_id',
        ),
    ),
);
